apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lhdboe6kk-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:c99e542d7b624dc48d6e45555678b6edd28aeeed@sha256:c00c1ebc20658be6f6f5a5f9229c2b07f255ee975ec19d17c90a2044f135e455
          name: container-image
